#!/usr/bin/env python3

import argparse
import json
import os
import sys

import packaging.specifiers
import packaging.version
import requests
import yaml

parser = argparse.ArgumentParser()
parser.add_argument("filename")
parser.add_argument("--include-devel", action="store_true")
parser.add_argument("--include-pre", action="store_true")
args = parser.parse_args()

with open(args.filename) as metafile:
    metadata = yaml.safe_load(metafile)

requirement = packaging.specifiers.SpecifierSet(metadata["requires_ansible"])

core_versions = requests.get("https://pypi.org/simple/ansible-core/", headers={"Accept": "application/vnd.pypi.simple.v1+json"}).json()["versions"]
static_versions = ["2.9.27", "2.10.17"]
available_versions = [packaging.version.Version(v) for v in core_versions+static_versions]

if not args.include_pre:
    available_versions = filter(lambda v: not v.is_prerelease, available_versions)

available_versions = filter(lambda v: v.major >= 2, available_versions)

branches = set()
for version in available_versions:
    if requirement.contains(f"{version.major}.{version.minor}.99"):
        branches.add(f"stable-{version.major}.{version.minor}")

if args.include_devel:
    branches.add("devel")

versions = sorted(branches)

if os.environ.get("GITHUB_ACTIONS"):
    if github_output := os.environ.get("GITHUB_OUTPUT"):
        output = open(github_output, "a")
    else:
        output = sys.stdout
    print(f"ansible={json.dumps(versions)}", file=output)

print(f"Determined compatible Ansible versions from {requirement}: {", ".join(versions)}")
