#!/usr/bin/env python3

import argparse
import json
import os
import sys

import packaging.specifiers
import yaml

MIN_VERSION = 9
MAX_VERSION = 19

parser = argparse.ArgumentParser()
parser.add_argument("filename")
parser.add_argument("--include-devel", action="store_true")
args = parser.parse_args()

with open(args.filename) as metafile:
    metadata = yaml.safe_load(metafile)

requirement = packaging.specifiers.SpecifierSet(metadata["requires_ansible"])

versions = []
for v in [f"2.{minor}" for minor in range(MIN_VERSION, MAX_VERSION+1)]:
    if requirement.contains(f"{v}.99"):
        versions.append(f"stable-{v}")

if args.include_devel:
    versions.append("devel")

if os.environ.get("GITHUB_ACTIONS"):
    if github_output := os.environ.get("GITHUB_OUTPUT"):
        output = open(github_output, "a")
    else:
        output = sys.stdout
    print(f"ansible={json.dumps(versions)}", file=output)

print(f"Determined compatible Ansible versions from {requirement}: {", ".join(versions)}")
